version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "intentee/release-action"
    commit-message:
      prefix: "github-aciton-update"
